### ISSUE TITLE
how to fix long content being spoken too fast?

### ISSUE THREAD

**Issue by hololeo** [lucasnewman/f5-tts-mlx#14]
First this is a great breakthrough project. Finally text to speech with 1 shot cloning on the mac!

I am trying to pipe in a text file for generation. It is only 11 lines long with 550 characters.

The output becomes an accelerated speech.

I am aware of the --speed and --duration flags. 

But is there anyway the program can determine these automagically based on the content length? 

Otherwise right now this is only useful for a couple lines of short text.

Any tips or work arounds?

**Comment by lucasnewman** [comment]
The effective length limit is 44 seconds total, so if you want to generate samples longer than that, you'll need to split on sentence boundaries or some other reasonable boundary in the text and generate each segment individually, then stitch them back together.

I saw that [this project](https://github.com/maiqingqiang/NotebookMLX) is doing something similar -- maybe you can get some inspiration from there! 🚀

**Comment by hololeo** [comment]
thank you for your response.

perhaps i packed two questions in one.

more importantly is the question - how can one determine the correct duration to give it. because longer lines of text make it speed up the reading.

and this be done programatically ?

or is it simply a matter of guesstimating by reading aloud the text and timing it. perhaps then counting words, sentences for an approximation?

**Comment by lucasnewman** [comment]
You could try calling the duration predictor directly with your reference audio and text to generate, but it's not going to predict anything longer than the max duration the model can generate: https://github.com/lucasnewman/f5-tts-mlx/blob/813780fec6e9b6071202b89c539d3f319ce53b02/f5_tts_mlx/cfm.py#L271

In general, the model is being accommodating when you're inputting a large volume of text by speeding up the speech to fit it all in. You'll get better results if you just break down the source material into chunks that are easily spoken, e.g. in 30 seconds (like a sentence or two) because you'll get a better duration estimation in that range.

**Comment by hololeo** [comment]
okay thanks i will dive into that

the issue im trying to find ways to speed up the inference process. so i assume giving it more text upfront would mean less starting over from scratch

ill post a separate issue on optimization ideas
